name: data_science
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.2.1
  - numpy=1.18.1
  - pandas=1.0.3
  - plotly=4.6.0
  - python=3.7.7
  - scipy=1.4.1
  - statsmodels=0.11.0
  - scikit-learn==0.22.2.post1
  - seaborn==0.10.0
  - folium
    