name: Build docker image

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/streamlit-stats

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create tag
      id: new_tag
      run: echo "TAG=$(date +%Y.%m.%d_%H.%M.%S)" >> "$GITHUB_OUTPUT"

    - name: Build Image
      env:
        TAG: ${{ steps.new_tag.outputs.TAG }}
      run: |
        docker build . --file Dockerfile \
          --tag $IMAGE_NAME:latest \
          --tag $IMAGE_NAME:$TAG

    - name: Docker login
      if: github.ref_name == 'master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN}}

    - name: Docker push
      if: github.ref_name == 'master'
      env:
        TAG: ${{ steps.new_tag.outputs.TAG }}
      run: |
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest


  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    env:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ubuntu@stats.eytanohana.com
    steps:
      - name: Login to EC2
        run: |
          echo $EC2_SSH_KEY > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'echo hiiiii'




