name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    uses: ./.github/workflows/docker-build.yml

  deploy:
    name: Push Image
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      run: docker login -u eohana98 -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Docker push
      run: |
        docker push eohana98/streamlit-stats:latest
        docker push eohana98/streamlit-stats:${{ github.run_number }}

