name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_push:
    name: Build Image and Push to Docker Hub

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: docker build . --file Dockerfile --tag eohana98/streamlit-stats
    - name: Docker Login
      run: docker login -u eohana98 -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Docker push
      run: docker push eohana98/streamlit-stats
