name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build Image

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: docker build . --file Dockerfile --tag eohana98/streamlit-stats:latest --tag eohana98/streamlit-stats:${{ github.run_number }}

  deploy:
    name: Push Image
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged

    steps:
    - name: Docker Login
      run: docker login -u eohana98 -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Docker push
      run: |
        docker push eohana98/streamlit-stats:latest
        docker push eohana98/streamlit-stats:${{ github.run_number }}

