name: Build docker image

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/streamlit-stats

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create tag
      id: new_tag
      run: echo "TAG=$(date +%Y.%m.%d_%H.%M.%S)" >> "$GITHUB_OUTPUT"

    - name: Build Image
      env:
        TAG: ${{ steps.new_tag.outputs.TAG }}
      run: |
        docker build . --file Dockerfile \
          --tag $IMAGE_NAME:latest \
          --tag $IMAGE_NAME:$TAG

    - name: Docker login
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN}}

    - name: Docker push
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
      env:
        TAG: ${{ steps.new_tag.outputs.TAG }}
      run: |
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest
    #
